### ISSUE TITLE
route_iisue

### ISSUE THREAD

**Issue by ashishCDN0135** [asifshaikh86/googlemaproute#1]
the library just opening the app not drawing route as u mentioned

**Comment by MuhammadArsalanChishti** [comment]
@Override
    public void afterDraw(String result) {
    }
if there is something wrong this method throws exception in log. kindly show exception here.

**Comment by ashishCDN0135** [comment]
thanks for ur update,its the key issue regarding which i am facing problem all i can say great work in this library..u can close this issue...

**Comment by asifshaikh86** [comment]
@ashishCDN0135 Thanks now closing this issue.
